TOKEN_KEY: DragonBall_Token

ORDER_NO_KEY: Order_No

APP_PRIVATE_KEY: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCgXJCmeomj/9XuQ59NqVOwFcG44glyCU6NnGzyERw44xB35KOlHcwOwoOSic4RnorvhdbvOAH48SPeIEiR+FXnisNMUXaIixClovAAGDiVOXKg/NVlhUkEM7JXoCYMIFY5HIqqG1L65iUz1UAeshk5fmonnVVEIcPjRhcsMtWJ5p8UtulkpbjiE9igAFtH67Z+9sYBfLEH43+ZfgDtMFD+BvRUv78O+DzMTLBdCuG5K2t2LA1OaZTeDEquVsyPyTNd9YpSPjorxnd8851GVm30I71EFzP7tW7d1T9WeelGX1eiYrIUwknDsbBND/bx3x+JfwRCce/g5JbVbVOWF1spAgMBAAECggEAIMxN2X7ef+hnfN/fySaEs1L/2CyC+gvlQRlpPuk4+HmYeK0Ou0qo3avy9RmyR/BBQlQBbdPqs1u+lkPME+7SwxSidQ2ETNEEipwUsjBCAmNJipurmaP1FyLrqvhaT8idWfj4c2o7Qo2ntj47awvKFPRCCfAn7FNrmSRQwP10p0trafiMlQLjwEpSa/qpuh+aYox7yyR8HIS2wRZEkn58vnh3KQzZ1S/5DCXKMdJsyc5QRxKQLEqw23j77fCqeTtQA5Ep5dNs02R2WnCGMZsXmoipBe22P91P7o6zmNAp9QIuju2lpc2k4W2eeZ5ktkcf0druKKDL2j2KSBT7PrL8MQKBgQD2lLIG9A8OCDL1Ag0LbGKlEiuv1U4BUUNWQCwvtjdTkVqyt1NU/rViRcOu8G2SG+RhLA5CZ3zB0yIdAKB7IgBD9PU3yxf2TvLrV4aSx1Ent+64hG9G0kMEYNKtmX/eTvNrEGRwPzRM4JKMybRufRgsUZ0SjVe1mn+UY6CfNknK5wKBgQCmfLwbjbSF98knpB4jEzO5mxw/98UfYkUJOoNKIjYLT2P0lGidqu0/mA1G84Q0G5NlP+bNcejUc+xApSUBtmcMnU815ijjZe5UK2f8oMM+8lP3jytSlaF6r8MyVHkI9TQWaeHAM8NpxJedm2fJwtsnm0vnZwvuvRYBzWlT0SF3bwKBgEgFanJJetQ4ZNnXPYQmpjFcu1HiVaRg3fAlUkKlUEeiXwFwNnDO7J/FjMBeDULtzqjrO0b9/xyF1KLv+e+9IKK4u58OPPN+X8mJiQ76FKQrPxi55d6jr1tqBF8cRJLkMIkHAq8eZuJFfciNaZwUAamANQakLggnFjh7WQDn1GnlAoGAci3FjFgI4H/pUuh5SrDWnopEO5KffECW/BdHB0ajLeqKsKg/fzJEd4K+SFSl7F6lHaFPlsJyXZILCuK3mI8R6VLRijOJAzta0hravCU9AiSLdZKYsZCxKET2Z8QLJhuUV3LSQlC9ygHrwUldSr/6MRWOXusLAfZn62CGxdb9Tr0CgYBO4IdatXbwZMlK5EjiVfKP93XsxgGDVpAgR5+xqzl3wn7Ep9IKckcIlqgexx2TGuranjUnwLOqOLQjYtB3kE74Esq+fdVUbKdCxJtD+fulFOeKPKmCrRG1VZt9vBwKRa/e58y0reP3eeCnb0uZX3nMcJHcUjZmgV0cohoDc/Q+zg==

ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwCqxG1R44P3Tecr6HfUuAW36HvndcKGRyLZg40Jwn2wJUQAMhcd/t93xuTQydDuYBZ0zTBbSF9RRQ5iAXHI1VqtvrnKGxoXXXhR7DwWIlS5aP1XIKA+B0fVOVLnZFbh9LwiTdk7zoSZZ38EH4jJc3oH+A8EV+fMQzHeqbwMNS86AhelLK7ONUKd5kqi+M2Dhe99GWcJ8WyBtF1lxudh/NPRxCgfiAxR2aeQIKRx1NYxqw1tp1YTQq3P15Qhjg58blarVUG1ZkcREicezg8rgFeS2l956UZKps+bBBfPzJH3k+eac2AdPRwrWQhqufALG6LhGCa2RiFBK7NEfbCgtmQIDAQAB

SIGN_TYPE: RSA2

AlipayConfig.FORMAT: json


AlipayConfig.CHARSET: utf-8


APP_ID: 2016091300500821

buyer:
   user_account: jcjtsr2271@sandbox.com
   login_password: 111111
   pay_password: 111111
   user_name: 沙箱环境
   IDENTITY_CARD: 27249619900520633X

business:
    account: wkuyqi4216@sandbox.com
    UID: 2088102175426103
    login_password: 111111


constants:
    # QQ
    qqAppId: xxxxxxxx
    qqAppSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    qqRedirectUrl: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #WECAT
    weCatAppId: wxe6029b044d561465
    weCatAppSecret: ae8f292859a2676db0dd988281a12b10
    weCatRedirectUrl: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


