spring:
# 配置rabbitMQspring:
  rabbitmq:
    host: 120.78.170.24
    port: 5672
    username: bruce
    password: 103021
    virtual-host: spring-boot-vhost
  application:
    name: dragonBall
  datasource :
    url : jdbc:mysql://120.78.170.24:3306/test
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver
  redis.database : 0
  redis.host : 120.78.170.24
  redis.port : 6379
  redis.password : 103021
  redis.pool.max-total : 8
  redis.pool.max-wait : -1
  redis.pool.max-idle : 8
  redis.pool.min-idle : 0
  redis.pool.timeout : 10000
#  邮箱配置
  mail:
    port: 25
    username: lp103021@163.com
    password:
    protocol: smtp
    default-encoding: utf-8
    host: smtp.163.com

logging.level.com.dragon.dao.mapper : DEBUG
mybatis.mapper-locations : classpath:mappers/*.xml
server.port : 8082
server.servlet.context-path: /dragonBall

getWeChatTokenUrl: https://qyapi.weixin.qq.com/cgi-bin/gettoken
sendWeChatMessageUrl: https://qyapi.weixin.qq.com/cgi-bin/message/send
corpid: wwb39358a1127198d6
corpsecret: iZ5ZcrdEmVURIWUjOcFFZE7uxjPyuP90MvCO1aGyiMM
agentid: 1000002


#eureka:
#  client:
#    serviceUrl:
#      defaultZone : http://localhost:1111/eureka
#
#  # 显示ip地址  不写就显示主机名称
#  instance:
#    prefer-ip-address : true
#    instance-id: ${spring.application.name}






